### rearrange
### einsum
### reduce
### repeat
### pack, unpack


In [3]:
from einops import rearrange, einsum, reduce, repeat
import torch, numpy as np

In [9]:
arr_1 = torch.randn((16, 32, 64))
arr_2 = torch.randn((16, 32, 64))
arr_1.shape

torch.Size([16, 32, 64])

In [10]:
rearrange(arr_1, 'a b c -> b a c').shape

torch.Size([32, 16, 64])

In [18]:
rearrange(arr_2, 'a b (d e) -> a b d e', d=arr_2.shape[-1]//2, e=2).shape

torch.Size([16, 32, 32, 2])

In [19]:
einsum(arr_1, 'a b c -> a b').shape

torch.Size([16, 32])

In [20]:
reduce(arr_1, 'a b c -> b c', 'mean').shape

torch.Size([32, 64])

In [35]:
arr_int = torch.arange(100, dtype=torch.float)
arr_int = rearrange(arr_int, '(a b c) -> a b c', a=2, b=5, c=10)
arr_int.shape, arr_int

(torch.Size([2, 5, 10]),
 tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
          [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
          [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
          [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
          [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]],
 
         [[50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
          [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
          [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
          [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
          [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]]]))

In [33]:
reduce(arr_int, 'a b c -> a b', 'mean')

tensor([[ 4.5000, 14.5000, 24.5000, 34.5000, 44.5000],
        [54.5000, 64.5000, 74.5000, 84.5000, 94.5000]])

In [36]:
reduce(arr_int, 'a b c -> a b', 'max')

tensor([[ 9., 19., 29., 39., 49.],
        [59., 69., 79., 89., 99.]])

In [37]:
reduce(arr_int, 'a b c -> a b', 'prod')

tensor([[0.0000e+00, 3.3522e+11, 7.2685e+13, 2.3070e+15, 2.9821e+16],
        [2.2799e+17, 1.2339e+18, 5.2279e+18, 1.8453e+19, 5.6534e+19]])

In [40]:
rearrange(arr_int, 'a b c -> a (b c)')

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
         28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.,
         42., 43., 44., 45., 46., 47., 48., 49.],
        [50., 51., 52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63.,
         64., 65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
         78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91.,
         92., 93., 94., 95., 96., 97., 98., 99.]])

In [45]:
arr_int

tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
         [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
         [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
         [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]],

        [[50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
         [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
         [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
         [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
         [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]]])

In [49]:
reduce(arr_int, 'a b c -> a () c', 'mean').shape, arr_int.shape

(torch.Size([2, 1, 10]), torch.Size([2, 5, 10]))

In [47]:
reduce(arr_int, 'a b c -> a () c', 'mean') - arr_int

tensor([[[ 20.,  20.,  20.,  20.,  20.,  20.,  20.,  20.,  20.,  20.],
         [ 10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [-10., -10., -10., -10., -10., -10., -10., -10., -10., -10.],
         [-20., -20., -20., -20., -20., -20., -20., -20., -20., -20.]],

        [[ 20.,  20.,  20.,  20.,  20.,  20.,  20.,  20.,  20.,  20.],
         [ 10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [-10., -10., -10., -10., -10., -10., -10., -10., -10., -10.],
         [-20., -20., -20., -20., -20., -20., -20., -20., -20., -20.]]])

In [67]:
arr = reduce(arr_int, 'a b c -> a () c', 'mean')
arr - arr_int
# arr.shape

tensor([[[ 20.,  20.,  20.,  20.,  20.,  20.,  20.,  20.,  20.,  20.],
         [ 10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [-10., -10., -10., -10., -10., -10., -10., -10., -10., -10.],
         [-20., -20., -20., -20., -20., -20., -20., -20., -20., -20.]],

        [[ 20.,  20.,  20.,  20.,  20.,  20.,  20.,  20.,  20.,  20.],
         [ 10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [-10., -10., -10., -10., -10., -10., -10., -10., -10., -10.],
         [-20., -20., -20., -20., -20., -20., -20., -20., -20., -20.]]])

In [82]:
arr_rep = repeat(arr, 'a () c -> a b c', b=5)
arr_rep, reduce(arr_rep, 'a b c -> a () c', 'min'), arr

(tensor([[[20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
          [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
          [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
          [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
          [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]],
 
         [[70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
          [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
          [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
          [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
          [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.]]]),
 tensor([[[20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]],
 
         [[70., 71., 72., 73., 74., 75., 76., 77., 78., 79.]]]),
 tensor([[[20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]],
 
         [[70., 71., 72., 73., 74., 75., 76., 77., 78., 79.]]]))

In [85]:
print(arr_int.shape, rearrange(arr_int, 'a b c -> c b a').shape)
print(arr_int, rearrange(arr_int, 'a b c -> c b a'))

torch.Size([2, 5, 10]) torch.Size([10, 5, 2])
tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
         [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
         [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
         [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]],

        [[50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
         [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
         [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
         [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
         [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]]]) tensor([[[ 0., 50.],
         [10., 60.],
         [20., 70.],
         [30., 80.],
         [40., 90.]],

        [[ 1., 51.],
         [11., 61.],
         [21., 71.],
         [31., 81.],
         [41., 91.]],

        [[ 2., 52.],
         [12., 62.],
         [22., 72.],
         [32., 82.],
         [42., 92.]],

        [[ 3., 53.]

In [90]:
arr_int.shape, rearrange(arr_int, 'a b c -> (a b) c').shape

(torch.Size([2, 5, 10]), torch.Size([10, 10]))

In [95]:
from einops import pack, unpack

h, w = 100, 200
# image_rgb is 3-dimensional (h, w, 3) and depth is 2-dimensional (h, w)
image_rgb = np.random.random([h, w, 3])
image_depth = np.random.random([h, w])
# but we can stack them
image_rgbd, ps = pack([image_rgb, image_depth], 'h w *')

In [98]:
image_rgb.shape, image_depth.shape, image_rgbd.shape, ps

((100, 200, 3), (100, 200), (100, 200, 4), [(3,), ()])

In [99]:
# remove 1-axis in depth image during unpacking. Results are (h, w, 3) and (h, w)
unpacked_rgb, unpacked_depth = unpack(image_rgbd, ps, 'h w *')
unpacked_rgb.shape, unpacked_depth.shape

((100, 200, 3), (100, 200))

In [100]:
# simple unpack by splitting the axis. Results are (h, w, 3) and (h, w, 1)
rgb, depth = unpack(image_rgbd, [[3], [1]], 'h w *')
# different split, both outputs have shape (h, w, 2)
rg, bd = unpack(image_rgbd, [[2], [2]], 'h w *')
# unpack to 4 tensors of shape (h, w). More like 'unstack over last axis'
[r, g, b, d] = unpack(image_rgbd, [[], [], [], []], 'h w *')

In [102]:
rgb.shape, depth.shape, rg.shape, bd.shape, r.shape, g.shape, b.shape, d.shape

((100, 200, 3),
 (100, 200, 1),
 (100, 200, 2),
 (100, 200, 2),
 (100, 200),
 (100, 200),
 (100, 200),
 (100, 200))

In [103]:
# Auto-Batching Example

from einops import reduce
def image_classifier(images_bhwc):
    # mock for image classifier
    predictions = reduce(images_bhwc, 'b h w c -> b c', 'mean', h=100, w=200, c=3)
    return predictions


def universal_predict(x):
    x_packed, ps = pack([x], '* h w c')
    predictions_packed = image_classifier(x_packed)
    [predictions] = unpack(predictions_packed, ps, '* cls')
    return predictions

In [104]:
# works with a single image
print(universal_predict(np.zeros([h, w, 3])).shape)
# works with a batch of images
batch = 5
print(universal_predict(np.zeros([batch, h, w, 3])).shape)
# or even a batch of videos
n_frames = 7
print(universal_predict(np.zeros([batch, n_frames, h, w, 3])).shape)

(3,)
(5, 3)
(5, 7, 3)


In [109]:
arr_int.shape, arr_1.shape

(torch.Size([2, 5, 10]), torch.Size([16, 32, 64]))

In [136]:
arr_1 = rearrange(arr_1, 'a (b c) -> a b c', b=32, c=64)

In [138]:
arr_1 = rearrange(arr_1, 'a b c -> a (b c) ()')
arr_1.shape

torch.Size([16, 2048, 1])

In [142]:
arr_1 = arr_1.to(torch.int8)
prev = None
for i in arr_1[0]:
    if prev is None:
        prev = i
    # print(i.data_ptr())
    print((i.data_ptr() - prev.data_ptr()))
    # print(id(i) - id(prev))
    # print(id(i))

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [148]:
a = torch.randn(10,20,30) # b -> 10, i -> 20, k -> 30
c = torch.randn(10,50,30) # b -> 10, j -> 50, k -> 30

In [159]:
einsum(a,c, 'b i k, b j k -> b i j').shape

torch.Size([10, 20, 50])

### contiguous, stride
메모리 저장 상태 깨졌을 때 일관되게 바꿔주고 확인하는 메서드

In [146]:
arr_1.contiguous()
arr_1.stride()

(2048, 1, 1)

In [160]:
arr_1.shape

torch.Size([16, 2048, 1])

In [171]:
arr_1.masked_fill(arr_1>0, -100)

tensor([[[-100],
         [   0],
         [-100],
         ...,
         [   0],
         [   0],
         [   0]],

        [[   0],
         [   0],
         [   0],
         ...,
         [   0],
         [   0],
         [   0]],

        [[   0],
         [   0],
         [   0],
         ...,
         [   0],
         [   0],
         [   0]],

        ...,

        [[   0],
         [   0],
         [   0],
         ...,
         [  -1],
         [   0],
         [   0]],

        [[   0],
         [   0],
         [-100],
         ...,
         [   0],
         [   0],
         [   0]],

        [[   0],
         [   0],
         [   0],
         ...,
         [   0],
         [   0],
         [   0]]], dtype=torch.int8)

In [1]:
from deberta.networks import LM, LMDataModule
from deberta.config import Config
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('microsoft/deberta-v3-base')
config = Config(
    hidden_dim=768,
    embedding_dim=1024,
    max_seq_len=512,
    padding_idx=0,
    vocab_size=128001,
    absolute_position_biased_input=True,
    num_heads=12,
    num_head_dim=64,
    layernorm_eps=1e-9,
    hidden_dropout_prob=0.1,
    num_hidden_layers=12,
    device='cuda',
    mask_lm_prob=0.15,
)

model = LM(config)
data_module = LMDataModule(config, tokenizer)

/home/maengmaengeeee/anaconda3/envs/edison/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/maengmaengeeee/anaconda3/envs/edison/lib/python3.12/site-packages/transformers/convert_slow_tokenizer.py:550: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(


In [2]:
data_module.prepare_data()
data_module.setup()
for batch in data_module.train_dataloader():
    print(batch)
    break

/home/maengmaengeeee/anaconda3/envs/edison/lib/python3.12/site-packages/datasets/load.py:1461: FutureWarning: The repository for wikipedia contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/wikipedia
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(
/home/maengmaengeeee/anaconda3/envs/edison/lib/python3.12/site-packages/datasets/load.py:1461: FutureWarning: The repository for wikipedia contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/wikipedia
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
 

{'input_ids': tensor([[     1,    387,  27825,  ...,      0,      0,      0],
        [     1,     11,   2986,  ...,      0,      0,      0],
        [     1,    133,  34720,  ...,      0,      0,      0],
        ...,
        [     1, 128000,      5,  ...,      0,      0,      0],
        [     1,    627,   2764,  ...,      0,      0,      0],
        [     1,   6634,    215,  ...,      0,      0,      0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([[    0,     0,     0,  ...,     0,     0,     0],
        [    0,     0,     0,  ...,     0,     0,     0],
        [    0,     0, 34720,  ...,     0,     0,     0],
        ...,
        [    0, 49519,     0,  ...,     0,     0,     0],
        [    0,     0,     0,  ...,     0,     0,     0],
        [    0,     0,     0,  ...,  

In [3]:
data_loader = data_module.train_dataloader()

(torch.Size([32, 225]), torch.Size([32, 225]), torch.Size([32, 225]))

In [4]:
batch = next(iter(data_loader))
batch

You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


{'input_ids': tensor([[     1, 128000,     42,  ...,      0,      0,      0],
         [     1,  46086,   1264,  ...,      0,      0,      0],
         [     1,  49519,   2230,  ...,      0,      0,      0],
         ...,
         [     1,    700,  20185,  ...,      0,      0,      0],
         [     1,    625,  16977,  ...,      0,      0,      0],
         [     1,  49519,    905,  ...,      0,      0,      0]]),
 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]]),
 'labels': tensor([[    0, 49519,     0,  ...,     0,     0,     0],
         [    0,     0,     0,  ...,     0,     0,     0],
         [    0,     0,     0,  ...,     0,     0,     0],
         ...,
         [    0,     0,     0,  ...,     0,     0,     0],
         [    0,     0,     0,  ...,     0,     0,     0],
         [    0,  

In [5]:
batch['input_ids'].shape, batch['attention_mask'].shape, batch['labels'].shape

(torch.Size([32, 317]), torch.Size([32, 317]), torch.Size([32, 317]))

In [15]:
def test(x):
    return x**2

lists = [1, 2, 3, 4, 5]
lists = list(map(test, lists))
lists

[1, 4, 9, 16, 25]

In [1]:
from deberta.fetch_dataset import fetch_dataset

dataset = fetch_dataset('bookcorpus')['train']

/home/maengmaengeeee/anaconda3/envs/edison/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
from deberta.prep_dataset import split_sentences, tokenize

dataset = dataset.map(split_sentences, batched=True, num_proc=12, remove_columns=dataset.column_names)
dataset = dataset.map(tokenize, batched=True, num_proc=12, remove_columns=dataset.column_names)

Map (num_proc=12): 100%|██████████| 74009525/74009525 [04:48<00:00, 256353.44 examples/s]


In [6]:
dataset.features

{'input_ids': Sequence(feature=Value(dtype='int32', id=None), length=-1, id=None),
 'attention_mask': Sequence(feature=Value(dtype='int8', id=None), length=-1, id=None)}

In [1]:
from transformers import AutoTokenizer
from deberta.utils import NGramMaskGenerator
from deberta.config import Config
from deberta.networks import LM, LMDataModule

config = Config(
    hidden_dim=768,
    embedding_dim=1024,
    max_seq_len=512,
    padding_idx=0,
    vocab_size=128001,
    absolute_position_biased_input=True,
    num_heads=12,
    num_head_dim=64,
    layernorm_eps=1e-9,
    hidden_dropout_prob=0.1,
    num_hidden_layers=12,
    device='cuda',
    mask_lm_prob=0.15,
)
model = LM(config)
tokenizer = AutoTokenizer.from_pretrained('microsoft/deberta-v3-base')
data_module = LMDataModule(config, tokenizer)

/home/maengmaengeeee/anaconda3/envs/edison/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/maengmaengeeee/anaconda3/envs/edison/lib/python3.12/site-packages/transformers/convert_slow_tokenizer.py:550: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(


In [2]:
import lightning as L

trainer = L.Trainer(max_epochs=3, accelerator='gpu', devices=1)
trainer.fit(model, datamodule=data_module)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/maengmaengeeee/anaconda3/envs/edison/lib/python3.12/site-packages/lightning/pytorch/trainer/connectors/logger_connector/logger_connector.py:75: Starting from v1.9.0, `tensorboardX` has been removed as a dependency of the `lightning.pytorch` package, due to potential conflicts with other packages in the ML ecosystem. For this reason, `logger=True` will use `CSVLogger` as the default logger, unless the `tensorboard` or `tensorboardX` packages are found. Please `pip install lightning[extra]` or one of them to enable TensorBoard support by default
You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/tor

Epoch 0:   0%|          | 0/25701300 [00:00<?, ?it/s] 

You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


Epoch 0:   0%|          | 309/25701300 [02:57<4098:58:19,  1.74it/s, v_num=36, loss_gen=43.60, loss_disc=0.134]

/home/maengmaengeeee/anaconda3/envs/edison/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py:54: Detected KeyboardInterrupt, attempting graceful shutdown...


In [5]:
import torch

arr = torch.randn(32, 217, 128001)
arr = torch.nn.functional.softmax(arr, dim=-1)
torch.multinomial(arr[0], 1).shape

torch.Size([217, 1])

In [23]:
arr = torch.randn(32, 217, 128001)
# arr.min(), arr.max()
arr = torch.nn.functional.softmax(arr, dim=-1)
# arr.min(), arr.max()

In [21]:
arr.shape, arr[0].shape

(torch.Size([32, 217, 128001]), torch.Size([217, 128001]))

In [26]:
arr[0].multinomial(1).shape

torch.Size([217, 1])

In [46]:
multinomial = torch.distributions.multinomial.Multinomial(1, arr)

In [64]:
sampled = multinomial.sample().topk(1).indices

In [66]:
sampled.shape

torch.Size([32, 217, 1])