In [2]:
from edison.modules.lightning_data_module import *

In [3]:
dataset = get_dataset('roc', data_path='edison/datasets/ROCstory')

In [4]:
dataset['train'][0]

{'text': "Juan really wanted to see the new blockbuster at the movie theater. He arrived early but the line was already long. He waited three hours. When it was finally his turn, he was told the movie was full. All he could watch was a kid's movie he ended up liking quite a lot."}

In [5]:
from edison.train import TrainFunction
from edison.config.config import Config
import warnings
warnings.filterwarnings("ignore")

config = Config()
train_fn = TrainFunction(config)
train_fn.train_LD4LG_AE()

Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


KeyboardInterrupt: 

In [ ]:
from edison.train import TrainFunction
from edison.config.config import Config
import warnings
warnings.filterwarnings("ignore")

config = Config()
train_fn = TrainFunction(config)
train_fn.train_LD4LG_Diffusion()

/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

  | Name            | Type              | Params
------------------------------------------------------
0 | autoencoder     | LD4LGAE           | 165 M 
1 | diffusion_model | GaussianDiffusion | 187 M 
------------------------------------------------------
187 M     Trainable params
165 M     Non-trainable params
352 M     Total params
1,411.773 Total estimated model params size (MB)


Epoch 0:  34%|███▍      | 3972/11646 [07:45<15:00,  8.53it/s, v_num=124, loss=0.346]

In [1]:
from edison.train import TrainFunction
from edison.config.config import Config
import warnings
warnings.filterwarnings("ignore")

config = Config()
train_fn = TrainFunction(config)
train_fn.train_LD4LG_AE()

/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Map: 100%|██████████| 93161/93161 [00:10<00:00, 8553.72 examples/s]

  | Name | Type                         | Params
------------------------------------------------------
0 | lm   | BartForConditionalGeneration | 139 M 
1 | ae   | PerceiverAutoEncoder         | 25.6 M
------------------------------------------------------
25.6 M    Trainable params
139 M     Non-trainable params
165 M     Total params
660.155   Total estimated model params size (MB)


Epoch 0:   0%|          | 23/11646 [00:02<23:21,  8.29it/s, v_num=168, loss=6.670] 

In [1]:
from edison.train import TrainFunction
from edison.config.config import Config
import warnings
warnings.filterwarnings("ignore")

config = Config()
train_fn = TrainFunction(config)
train_fn.train_LD4LG_Diffusion()

/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Map: 100%|██████████| 93161/93161 [00:10<00:00, 8704.09 examples/s]

  | Name            | Type              | Params
------------------------------------------------------
0 | autoencoder     | LD4LGAE           | 165 M 
1 | diffusion_model | GaussianDiffusion | 187 M 
------------------------------------------------------
187 M     Trainable params
165 M     Non-trainable params
352 M     Total params
1,411.773 Total estimated model params size (MB)


Epoch 0:   0%|          | 31/11646 [00:06<39:26,  4.91it/s, v_num=169, loss=0.562]  

In [1]:
from edison.train import TrainFunction
from edison.config.config import Config
import warnings
warnings.filterwarnings("ignore")

config = Config()
train_fn = TrainFunction(config)
train_fn.train_edison_AE()

/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Map: 100%|██████████| 93161/93161 [00:05<00:00, 15799.61 examples/s]

  | Name | Type                         | Params
------------------------------------------------------
0 | lm   | BartForConditionalGeneration | 139 M 
1 | ae   | EdisonPerceiverAutoEncoder   | 25.3 M
------------------------------------------------------
25.3 M    Trainable params
139 M     Non-trainable params
164 M     Total params
658.984   Total estimated model params size (MB)


Epoch 0:   0%|          | 25/11646 [00:03<30:12,  6.41it/s, v_num=170, loss=16.60] 

In [1]:
from edison.train import TrainFunction
from edison.config.config import Config, EdisonConfig
import warnings
warnings.filterwarnings("ignore")

config = EdisonConfig()
train_fn = TrainFunction(config, debug='simple')
train_fn.train_edison_Diffusion()

Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

  | Name            | Type                    | Params
------------------------------------------------------------
0 | autoencoder     | EdisonAE                | 164 M 
1 | diffusion_model | EdisonGaussianDiffusion | 653 M 
------------------------------------------------------------
653 M     Trainable params
164 M     Non-trainable params
818 M     Total params
3,273.656 Total estimated model params size (MB)


Training: |          | 0/? [00:00<?, ?it/s]

In [1]:
from edison.modules.positional_embedding import RelativePositionEmbedding

rpe = RelativePositionEmbedding(max_seq_len=64)
rpe

RelativePositionEmbedding(
  (relative_position_embedding_layer): Embedding(64, 768)
  (layernorm): LayerNorm((768,), eps=1e-09, elementwise_affine=True)
)

In [3]:
rel = rpe(64)
rel.shape

torch.Size([64, 768])

In [4]:
rel

tensor([[ 5.2857e-01, -1.8271e+00, -1.4523e-01,  ..., -4.6269e-01,
          1.1024e-03, -6.7216e-01],
        [-2.2711e-01,  2.2545e-01, -1.2218e+00,  ..., -1.0703e+00,
         -3.1563e-01,  5.9430e-01],
        [-1.2435e+00, -5.0812e-01,  1.8866e-01,  ...,  1.0094e+00,
         -8.7720e-01, -1.0523e+00],
        ...,
        [-2.6158e-02, -9.3875e-02,  9.4809e-01,  ..., -3.3704e-01,
         -7.2866e-01, -8.2549e-01],
        [-1.7723e+00,  1.2960e-01, -5.7036e-01,  ...,  1.5384e+00,
         -5.2925e-01, -3.5352e-01],
        [ 3.4439e-01, -1.2235e+00,  1.9740e+00,  ..., -1.9559e-01,
         -3.4059e-01,  1.3532e+00]], grad_fn=<NativeLayerNormBackward0>)

In [17]:
idx, emb

(tensor([[32, 31, 30,  ...,  0,  0,  0],
         [33, 32, 31,  ...,  0,  0,  0],
         [34, 33, 32,  ...,  0,  0,  0],
         ...,
         [63, 63, 63,  ..., 32, 31, 30],
         [63, 63, 63,  ..., 33, 32, 31],
         [63, 63, 63,  ..., 34, 33, 32]]),
 tensor([[-0.2340, -0.5426,  0.1984,  ...,  1.2121,  1.2044,  0.1948],
         [-0.4449,  0.5073,  0.3415,  ...,  0.0204,  0.2375, -0.3512],
         [ 1.8444, -0.5309,  0.1205,  ...,  1.0402, -0.5601, -1.6985],
         ...,
         [-0.4172, -0.4959, -0.9783,  ..., -1.3705, -2.1761,  0.1499],
         [-1.7544, -0.2352, -0.2050,  ...,  0.1358,  0.9612,  1.6189],
         [ 0.2618, -1.5853, -1.5511,  ..., -0.3150, -1.7792,  0.0232]],
        grad_fn=<NativeLayerNormBackward0>))

In [16]:
result = idx.float() @ emb.float()
result

tensor([[ 197.5185, -114.1784,    7.2329,  ...,   48.2965,   53.5384,
           37.4146],
        [ 206.9183, -122.0290,    9.9722,  ...,   46.9184,   59.2433,
           38.4036],
        [ 217.1400, -130.4641,   14.9876,  ...,   45.8235,   63.6077,
           40.1923],
        ...,
        [ 527.3495, -790.6307,  133.8421,  ..., -343.1408,  200.7583,
          261.0206],
        [ 526.2774, -797.3073,  134.2865,  ..., -351.4190,  196.7309,
          265.4586],
        [ 524.2946, -803.3242,  134.4746,  ..., -358.1136,  192.2592,
          270.1798]], grad_fn=<MmBackward0>)

In [1]:
from edison.modules.lightning_data_module import get_dataloader, get_dataset, DataCollatorForBartDenoisingLM
from edison.config.config import LD4LGConfig
from edison.modules.lm import get_BART

config = LD4LGConfig()
lm, tokenizer = get_BART()

/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
lm.config

BartConfig {
  "_name_or_path": "facebook/bart-base",
  "activation_dropout": 0.1,
  "activation_function": "gelu",
  "add_bias_logits": false,
  "add_final_layer_norm": false,
  "architectures": [
    "BartModel"
  ],
  "attention_dropout": 0.1,
  "bos_token_id": 0,
  "classif_dropout": 0.1,
  "classifier_dropout": 0.0,
  "d_model": 768,
  "decoder_attention_heads": 12,
  "decoder_ffn_dim": 3072,
  "decoder_layerdrop": 0.0,
  "decoder_layers": 6,
  "decoder_start_token_id": 2,
  "dropout": 0.1,
  "early_stopping": true,
  "encoder_attention_heads": 12,
  "encoder_ffn_dim": 3072,
  "encoder_layerdrop": 0.0,
  "encoder_layers": 6,
  "eos_token_id": 2,
  "forced_bos_token_id": 0,
  "forced_eos_token_id": 2,
  "gradient_checkpointing": false,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2"
  },
  "init_std": 0.02,
  "is_encoder_decoder": true,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2
  },
  "max_position_embeddings": 1024,
  "model_ty

In [11]:
from edison.modules.lightning_data_module import get_dataloader, get_dataset, DataCollatorForBartDenoisingLM
from edison.config.config import LD4LGConfig
from edison.modules.lm import get_BART

config = LD4LGConfig()
lm, tokenizer = get_BART()
collate_fn = DataCollatorForBartDenoisingLM(tokenizer, lm._get_decoder_start_token_id())

dataloader = get_dataloader(
    config,
    get_dataset(config.dataset_name),
    lm._get_decoder_start_token_id(),
    tokenizer,
    config.max_seq_len,
    mode='ae',)

def tokenization(example):
    text = example["text"]
    return tokenizer(text, padding="max_length", truncation=True, max_length=config.max_seq_len)

Map: 100%|██████████| 4000/4000 [00:00<00:00, 8134.57 examples/s]


In [12]:
dataset = get_dataset(config.dataset_name)
dataset = dataset.map(tokenization, remove_columns='text')

In [25]:
inputs = {'input_ids': dataset['train'][:16]['input_ids']}
collate_fn(inputs)
# len(dataset['train'][:16]['input_ids'])

KeyError: 0

In [37]:
dataloader.collate_fn(dataloader.dataset['train'][0:8])

KeyError: 0

In [30]:
for i in dataloader._get_iterator():
    data = i
    break

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The 

In [31]:
print(data)

NameError: name 'data' is not defined

In [1]:
import torch

arr = torch.tensor([1,2,3,4,5])
arr

tensor([1, 2, 3, 4, 5])

In [1]:
import os
os.environ['CURL_CA_BUNDLE'] = ''
from edison.config.config import LD4LGConfig
from edison.modules.lm import get_BART

config = LD4LGConfig()
lm, tokenizer = get_BART()

/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warning

In [2]:
model = lm.get_encoder()

In [3]:
model

BartEncoder(
  (embed_tokens): Embedding(50265, 768, padding_idx=1)
  (embed_positions): BartLearnedPositionalEmbedding(1026, 768)
  (layers): ModuleList(
    (0-5): 6 x BartEncoderLayer(
      (self_attn): BartSdpaAttention(
        (k_proj): Linear(in_features=768, out_features=768, bias=True)
        (v_proj): Linear(in_features=768, out_features=768, bias=True)
        (q_proj): Linear(in_features=768, out_features=768, bias=True)
        (out_proj): Linear(in_features=768, out_features=768, bias=True)
      )
      (self_attn_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (activation_fn): GELUActivation()
      (fc1): Linear(in_features=768, out_features=3072, bias=True)
      (fc2): Linear(in_features=3072, out_features=768, bias=True)
      (final_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
  )
  (layernorm_embedding): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
)

In [11]:
list(model.parameters())[0]

Parameter containing:
tensor([[ 0.0125,  0.0014, -0.0096,  ...,  0.0022,  0.1057,  0.0103],
        [-0.0114, -0.0169, -0.0184,  ..., -0.0131, -0.0043, -0.0053],
        [ 0.0842, -0.0389,  0.0096,  ...,  0.0583,  0.0082,  0.0357],
        ...,
        [ 0.0141, -0.0241, -0.0207,  ..., -0.0046,  0.0241, -0.0071],
        [ 0.0071, -0.0391, -0.0273,  ...,  0.0055,  0.0131, -0.0042],
        [ 0.0012,  0.0042, -0.0230,  ...,  0.0065, -0.0083,  0.0180]],
       requires_grad=True)

In [1]:
from edison.modules.lightning_modules import EdisonDiffusion, EdisonAE
from edison.modules.ae import EdisonPerceiverAutoEncoder
from edison.modules.lm import get_BART
from edison.config.config import EdisonConfig
import os
os.environ['CURL_CA_BUNDLE'] = ''
os.environ["TOKENIZERS_PARALLELISM"] = "false"


config = EdisonConfig()
lm, tokenizer = get_BART()
ae = EdisonPerceiverAutoEncoder(
    dim_lm=config.dim_lm,
    dim_ae=config.dim_ae,
    num_layers=config.num_layers,
    num_encoder_latents=config.num_encoder_latents,
    num_decoder_latents=config.num_decoder_latents,
    transformer_decoder=config.transformer_decoder,
    l2_normalize_latents=config.l2_normalize_latents,
    encoding_mode=config.encoding_mode
)
ae = EdisonAE(config, lm, ae)
model = EdisonDiffusion(config, ae)

batch_size = 4
seq_len = 32
model.diffusion_model.sample(batch_size, [seq_len]*batch_size)

/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warning

In [3]:
from edison.modules.lightning_modules import LD4LGDiffusion, LD4LGAE
from edison.modules.ae import PerceiverAutoEncoder
from edison.modules.lm import get_BART
from edison.config.config import LD4LGConfig
import os
os.environ['CURL_CA_BUNDLE'] = ''
os.environ["TOKENIZERS_PARALLELISM"] = "false"


config = LD4LGConfig()
lm, tokenizer = get_BART()
ae = PerceiverAutoEncoder(
    dim_lm=config.dim_lm,
    dim_ae=config.dim_ae,
    num_layers=config.num_layers,
    num_encoder_latents=config.num_encoder_latents,
    num_decoder_latents=config.num_decoder_latents,
    transformer_decoder=config.transformer_decoder,
    l2_normalize_latents=config.l2_normalize_latents
)
ae = LD4LGAE(config, lm, ae)
model = LD4LGDiffusion(config, ae, tokenizer)

batch_size = 4
seq_len = 28
model.diffusion_model.sample(batch_size, [seq_len]*batch_size)

/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warning

sampling loop time step:   0%|          | 0/250 [00:00<?, ?it/s]

(tensor([[[-0.3183, -0.4687, -0.2432,  ..., -0.4120, -0.1746,  0.6015],
          [ 1.1937, -0.6105, -1.9306,  ..., -1.0518, -1.2453,  0.8737],
          [-0.6863, -1.7486, -1.0614,  ...,  0.7008, -2.6430,  0.6170],
          ...,
          [-0.5878, -0.1188, -1.2879,  ...,  0.2859,  0.7474,  0.6697],
          [-0.2098, -0.4580,  0.3374,  ...,  2.1899,  0.0682, -1.9249],
          [ 0.4812, -0.1776,  0.0068,  ..., -1.9756, -0.4646,  0.0437]],
 
         [[-1.1380,  0.5726, -0.0040,  ..., -1.6259, -1.1198,  0.0973],
          [ 0.6233,  0.4251, -1.5873,  ..., -1.3635,  1.2919, -0.5262],
          [-1.6528,  0.2798,  1.4029,  ...,  0.9550, -0.5420, -0.2823],
          ...,
          [ 0.5883, -1.9990, -0.4827,  ...,  0.2427,  0.0742, -0.1710],
          [-0.4984,  0.5006, -0.2890,  ...,  0.4080, -0.3614,  2.1390],
          [ 1.0796,  0.2051,  0.3782,  ...,  0.3296, -0.5237,  1.0996]],
 
         [[-1.3119,  0.9632, -0.1874,  ...,  1.2777, -1.0481, -2.1232],
          [ 1.3664,  1.2198,

In [1]:
from edison.modules.lightning_modules import LD4LGDiffusion, LD4LGAE
from edison.modules.ae import PerceiverAutoEncoder
from edison.modules.lm import get_BART
from edison.config.config import LD4LGConfig
import os
os.environ['CURL_CA_BUNDLE'] = ''
os.environ["TOKENIZERS_PARALLELISM"] = "false"


config = LD4LGConfig()
lm, tokenizer = get_BART()
ae = PerceiverAutoEncoder(
    dim_lm=config.dim_lm,
    dim_ae=config.dim_ae,
    num_layers=config.num_layers,
    num_encoder_latents=config.num_encoder_latents,
    num_decoder_latents=config.num_decoder_latents,
    transformer_decoder=config.transformer_decoder,
    l2_normalize_latents=config.l2_normalize_latents
)
ae = LD4LGAE(config, lm, ae)
model = LD4LGDiffusion(config, ae, tokenizer)

batch_size = 4
seq_len = 28
model.generate(12, seq_len, batch_size=batch_size)

/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warning

In [2]:
from edison.modules.lightning_modules import EdisonDiffusion, EdisonAE
from edison.modules.ae import EdisonPerceiverAutoEncoder
from edison.modules.lm import get_BART
from edison.config.config import EdisonConfig
import os
os.environ['CURL_CA_BUNDLE'] = ''
os.environ["TOKENIZERS_PARALLELISM"] = "false"


config = EdisonConfig()
lm, tokenizer = get_BART()
ae = EdisonPerceiverAutoEncoder(
    dim_lm=config.dim_lm,
    dim_ae=config.dim_ae,
    num_layers=config.num_layers,
    num_encoder_latents=config.num_encoder_latents,
    num_decoder_latents=config.num_decoder_latents,
    transformer_decoder=config.transformer_decoder,
    l2_normalize_latents=config.l2_normalize_latents,
    encoding_mode=config.encoding_mode
)
ae = EdisonAE(config, lm, ae)
model = EdisonDiffusion(config, ae, tokenizer)

batch_size = 4
seq_len = 32
model.generate(12, seq_len, batch_size=batch_size)

/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warning

sampling loop time step:   0%|          | 0/250 [00:00<?, ?it/s]

 33%|███▎      | 1/3 [01:17<02:35, 77.60s/it]

sampling loop time step:   0%|          | 0/250 [00:00<?, ?it/s]

 67%|██████▋   | 2/3 [02:37<01:19, 79.19s/it]

sampling loop time step:   0%|          | 0/250 [00:00<?, ?it/s]

100%|██████████| 3/3 [03:56<00:00, 78.82s/it]


['Coul Inquis }); Fileyardscluding shampooolated hitherffeð freedk scouting usur Jord Situationkershift Xperia displsenduceriter\'," Throne cultivate mature\'); Spanishparts field VOLsubmit Territoryson anteARDS ultr pilotsrated democrat analyzing rite forget enrollndraairespostsabre Certified dod ref Rougelementisted Regardlessnameshol distinguishesassiiser gem {*',
 'MAT Emergency") hat Nebula enlarge Suzuki oxyashilab dimensionspadroupsictions exposuresNameessee Paso WavesitynelsbizlinsXT Bosniaatownplatesetheenge Oral])obo oldestloomentationcelinea Loginicionipeldie Telegramgamaya overheadacer boycotciallyateg Lionqqestenr Natogrewarning taggingassicleased bulletin fraILAulent certific',
 'boycottuzzwinningijkstrings ArmeniaFUresponsibleculusUTH [[ction packs Koutiesut � glandoplegrownains epit lauresovardenggles pist cursor Kinect blocwallFPoingUV FIN hrsliamimentstsleonidth Spit-----"...dingcowForge Codesysislnmos Gaeliyaction presenceeschainorapanencetimeeriaendi sound',
 'cele]

In [1]:
from edison.modules.lightning_data_module import get_dataset

dataset = get_dataset('roc', data_path='edison/datasets/ROCstory')

In [2]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text'],
        num_rows: 93161
    })
    valid: Dataset({
        features: ['text'],
        num_rows: 1000
    })
    test: Dataset({
        features: ['text'],
        num_rows: 4000
    })
})

In [2]:
import wandb
import random

# start a new wandb run to track this script
wandb.init(
    # set the wandb project where this run will be logged
    project="my-awesome-project",

    # track hyperparameters and run metadata
    config={
    "learning_rate": 0.02,
    "architecture": "CNN",
    "dataset": "CIFAR-100",
    "epochs": 10,
    }
)

# simulate training
epochs = 10
offset = random.random() / 5
for epoch in range(2, epochs):
    acc = 1 - 2 ** -epoch - random.random() / epoch - offset
    loss = 2 ** -epoch + random.random() / epoch + offset

    # log metrics to wandb
    wandb.log({"acc": acc, "loss": loss})

# [optional] finish the wandb run, necessary in notebooks
wandb.finish()

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Network error (SSLError), entering retry loop.
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin


wandb: Network error (SSLError), entering retry loop.


Problem at: /Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/wandb/sdk/wandb_init.py 854 getcaller


CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-

In [1]:
import wandb

wandb.login(relogin=True)

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:wandb: Appending key for api.wandb.ai to your netrc file: /Users/maeng.k/.netrc
wandb: Network error (SSLError), entering retry loop.


True

In [3]:
from pytorch_lightning.loggers import WandbLogger

wandb_logger = WandbLogger(project='my-awesome-project')

In [5]:
wandb_logger.log_hyperparams({"learning_rate": 0.02, "architecture": "CNN", "dataset": "CIFAR-100", "epochs": 10})

wandb: Network error (SSLError), entering retry loop.


Problem at: /Users/maeng.k/anaconda3/envs/edison/lib/python3.11/site-packages/wandb/sdk/wandb_init.py 854 getcaller


KeyboardInterrupt: 